### ISSUE TITLE
Feature: Add Auditbeat

### ISSUE THREAD

**Issue by praseodym** [elastic/beats-docker#23]
[Auditbeat](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-overview.html) does not currently have a Docker image available, it would be great to have one.

**Comment by jarpy** [comment]
Absolutely. An image now exists, but I don't think it is useful yet, sorry.

See #25.

**Comment by jarpy** [comment]
We established in #25 that Auditbeat needs to be in the main process namespace (`--pid=host`).

With that flag, it works. 🎉
