### ISSUE TITLE
Mapping definition for [error] has unsupported parameters

### ISSUE THREAD

**Issue by ianseyer** [elastic/beats-docker#24]
I am using a lightly customized installation of all 6.0.0-beta1 beats.

However, When attempting to start them, they all spew this error:

```
 2017/08/22 19:58:16.455956 client.go:465: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Mapping definition for [error] has unsupported parameters:  [properties : {code={type=long}, message={norms=false, type=text}, type={ignore_above=1024, type=keyword}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [error] has unsupported parameters:  [properties : {code={type=long}, message={norms=false, type=text}, type={ignore_above=1024, type=keyword}}]"}}
```

I have set `setup.template.overwrite: true` in all of the config files, and I have also run `docker run --add-host "elasticsearch:xxx.xxx.xx.xx" docker.elastic.co/beats/filebeat:6.0.0-beta1 setup --template`

I am not sure how to interpret this error at all.

Running on amazonlinux, docker 17.03.1-ce, elasticsearch 5.

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there.

**Comment by ianseyer** [comment]
why reinvent the wheel?

**Comment by andrewkroh** [comment]
Are you asking why you should use https://discuss.elastic.co/c/beats instead of Github for your question? There is a much more active community of users on the forum that can help with resolving your issue.
