### ISSUE TITLE
Cannot share filebeat.yml with docker container

### ISSUE THREAD

**Issue by raztud** [elastic/beats-docker#36]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Beat Version: 
- Operating System: Ubuntu 16.04; Linux client 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Docker Version: Docker version 18.03.1-ce, build 9ee9f40
- Steps to Reproduce: 
According to https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
when I run: 
```docker run -v /root/filebeat-docker/filebeat.yml:/usr/share/filebeat/filebeat.yml   docker.elastic.co/beats/filebeat:6.2.4```

I get docker: ```
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'filebeat.yml')```

**Comment by andrewkroh** [comment]
> more than one namespace configured accessing 'output'

That sounds like a problem with you config. Do you have two different outputs enabled such as elasticsearch and logstash? You can only have one.

**Comment by kvch** [comment]
I am closing the issue as it has been inactive. If the problem persists open an issue in elastic/beats, as this repo is going to be archived: https://github.com/elastic/beats
