### ISSUE TITLE
Unable to run filebeat in docker with yml file mapping

### ISSUE THREAD

**Issue by rohitpatwari84** [elastic/beats-docker#47]
I get error while executing the below command - 

**sudo docker run -v /etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:6.4.0**

container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/etc/filebeat/filebeat.yml\\\" to rootfs \\\"/app/docker/devicemapper/mnt/e9a0e8d10a77d4f658c82511f60be50f4afe5598df8bb2f9c168f15d52ff0fd1/rootfs\\\" at \\\"/app/docker/devicemapper/mnt/e9a0e8d10a77d4f658c82511f60be50f4afe5598df8bb2f9c168f15d52ff0fd1/rootfs/usr/share/filebeat/filebeat.yml\\\" caused \\\"not a directory\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/etc/filebeat/filebeat.yml\\\" to rootfs \\\"/app/docker/devicemapper/mnt/e9a0e8d10a77d4f658c82511f60be50f4afe5598df8bb2f9c168f15d52ff0fd1/rootfs\\\" at \\\"/app/docker/devicemapper/mnt/e9a0e8d10a77d4f658c82511f60be50f4afe5598df8bb2f9c168f15d52ff0fd1/rootfs/usr/share/filebeat/filebeat.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
ERRO[0000] error waiting for container: context canceled

**Comment by webmat** [comment]
Usage discussions should be brought up in the forums, at https://discuss.elastic.co, look for the "Beats" section. 

GitHub issues should only be used for confirmed bugs or feature requests.

Thank you!
