### ISSUE TITLE
Use ENTRYPOINT, not just CMD in Dockerfile.

### ISSUE THREAD

**Issue by jarpy** [elastic/beats-docker#6]
Provide a nice ENTRYPOINT, so that people can do things like:

```
docker run docker.elastic.co/beats/metricbeat:5.3.0 -system.hostfs=/hostfs
```

See also: #5.

**Comment by exekias** [comment]
This was done in https://github.com/elastic/beats-docker/pull/14/files and https://github.com/elastic/beats-docker/pull/21
