### ISSUE TITLE
Feature: Add Ubuntu 16.04 base image support

### ISSUE THREAD

**Issue by apolloclark** [elastic/beats-docker#66]
I forked the repo and converted it to Ubuntu 16.04 base image:
https://github.com/apolloclark/packer-elk-docker

What’s the best way to open a PR for this?

**Comment by jarpy** [comment]
Interestingly enough, the Elastic Docker images used to be based on Ubuntu, but [we switched to a CentOS base](https://github.com/elastic/beats-docker/commit/e4fd1a79664cf3fdc81bef0362f38167609dfd80) as a predictable and stable foundation.

We don't intend to support multiple base variants of our images at this stage, and if we did, we'd need to synchronize that support across the Elasticsearch, Logstash, Kibana, Beats and APM images. As you can imagine, that would create a lot of future work maintaining multiple base variants across all those product images.

Ideally, we hope that users won't much care what libraries are inside the container. After all, that's really the big promise of ready-to-run containers. Out of professional curiosity, what does an Ubuntu based image enable for you?

**Comment by jarpy** [comment]
Thanks for the info. It's always good to hear about real world use cases at scale.

Highlighting this for @jethr0null (who I'm sure will read it anyway!).

**Comment by apolloclark** [comment]
@jarpy Definitely, thanks! My daily build pipeline is Jenkins + Gradle + Terraform + Packer + Ansible + Serverspec to AWS EC2, which I'm now converting to use Kubernetes + Docker:
https://github.com/apolloclark/tf-aws

I prefer using Ansible, instead of the Dockerfile, since it makes it easy to templatize configuration variables in a YAML file, versus Bash env variables, which is easier to maintain. I prefer using Packer to build containers, since it let's me reuse a single provisioning tool across multiple providers (Docker, Virtualbox, VMWare, AWS EC2, Azure VM). Terraform lets me use a single tool across multiple cloud providers, to provision cloud resources like load balancers.

**Comment by jarpy** [comment]
Closing this issue. If we pursue alternative image bases, the work would be best tracked on the stack-wide product roadmap.
